# Generated by Django 2.0 on 2020-08-06 17:34
from os import path

from django.db import migrations, models
import django.db.models.deletion

def run_init_sql(apps, schema_editor):
    file_path = path.join(path.dirname(__file__), 'sql_script', 'init.sql')
    sql = open(file_path).read()
    schema_editor.execute(sql)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, null=True, unique=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('date_of_innaugration', models.DateField(null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='KeyResults',
            fields=[
                ('keyresult_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('keyresult_text', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Complete', 'COMPLETE')], max_length=12, null=True)),
                ('due_date', models.DateField(null=True)),
                ('updated_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'keyresults',
            },
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('objective_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('objective_text', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'objectives',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('average_pay', models.CharField(max_length=10, null=True)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Teams')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='team_lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Users'),
        ),
        migrations.AddField(
            model_name='objectives',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Users'),
        ),
        migrations.AddField(
            model_name='keyresults',
            name='objective_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Objectives'),
        ),
        migrations.RunPython(run_init_sql),
    ]
